import type { ThinkTankState } from "./types";

export const createInitialState=():ThinkTankState=>({
  sessionId:"PHI-0001",
  seed:"369042",
  mode:"council",
  routerPolicy:"council-broadcast",
  phase:"intake",
  seq:0,
  operatorPrompt:"",
  gateThreshold:.75,
  gateScore:null,
  gateBreakdown:null,
  claimGovernance:null,
  argumentGovernance:null,
  decisionDossiers:[],
  decisionOverrides:[],
  dossierSeals:[],
  dossierSealVerifications:[],
  dossierTransparencyEntries:[],
  dossierTransparencyCheckpoints:[],
  dossierTransparencyWitnesses:[],
  dossierTransparencyWitnessVerifications:[],
  evidenceRefs:[],
  evidenceExcerpts:[],
  claims:[],
  claimBindings:[],
  claimReviews:[],
  argumentReviews:[],
  researchSearches:[],
  researchCandidates:[],
  synthesisWithheld:false,
  assignments:[
    {roleId:"vessie",seatId:"local"},
    {roleId:"dreamer",seatId:"kimi"},
    {roleId:"builder",seatId:"local"},
    {roleId:"challenger",seatId:"openai"},
    {roleId:"archivist",seatId:"kimi"}
  ],
  pinnedAssignments:{},
  assignmentScores:{vessie:4.1,dreamer:4.8,builder:4.7,challenger:5,archivist:4.8},
  assignmentReasons:{
    vessie:"Bootstrap assignment before Crane Fly planning.",
    dreamer:"Bootstrap assignment before Crane Fly planning.",
    builder:"Bootstrap assignment before Crane Fly planning.",
    challenger:"Bootstrap assignment before Crane Fly planning.",
    archivist:"Bootstrap assignment before Crane Fly planning."
  },
  assignmentOrigins:{
    vessie:"bootstrap",
    dreamer:"bootstrap",
    builder:"bootstrap",
    challenger:"bootstrap",
    archivist:"bootstrap"
  },
  seatStatus:{openai:"online",kimi:"online",local:"online"},
  terminalStates:{vessie:"idle",dreamer:"idle",builder:"idle",challenger:"idle",archivist:"idle"},
  lastUtterance:{},
  turnPlan:null,
  currentRound:0,
  speakerIndex:0,
  currentSpeaker:null,
  objectionCount:0,
  outputLabel:null,
  actionAllowed:false,
  governanceReason:"",
  faultCode:null,
  events:[]
});
